---
name: "🐛 Bug Report"
description: Report a bug
title: "(short issue description)"
labels: [bug, needs-triage]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What is the problem? Provide a clear description of your issue and the steps you took that produced it.
    validations:
      required: true
  - type: textarea
    id: modelname
    attributes:
      label: Model Name
      description: Provide Model Name
    validations:
      required: true
  - type: textarea
    id: workloadtype
    attributes:
      label: Describe the workload type 
      description: Note the type of workload (such as Inference or Training) and any specific details about the workload configuration.
    validations:
      required: true
  - type: textarea
    id: instancetype
    attributes:
      label: Instance Type
      description: |
       Provide the AWS EC2 instance type you used to run the workload (such as `inf2.xlarge`, `trn1.32xlarge`, `trn2.48xlarge` etc.)
    validations:
      required: true
  - type: textarea
    id: release
    attributes:
      label: Release version 
      description: |
        Provide the Neuron SDK release version (such as `2.25.0`) you are using, and all relevant Neuron component versions. 
        ```
        apt list --installed | grep -i -e neuron
        pip list | grep -i -e neuron -e torch -e transformers -e jax
        ```
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: |
        Provide the type of the model and links to any tutorials you may have used, as additional context.
        Provide a self-contained, concise snippet of code that can be used to reproduce the issue.
        For more complex issues provide a repo with the smallest sample that reproduces the bug.
        
        Avoid including business logic or unrelated code as it makes diagnosis more difficult.
        The code sample should be an SSCCE. See http://sscce.org/ for details. In short, please provide a code sample that we can copy/paste, run and reproduce.
    validations:
      required: true
  - type: checkboxes
    id: regression
    attributes:
      label: Regression Issue
      description: Is this as regression (did it work in a previous version and not now)?
        If this is a regression, provide the Neuron SDK release version where this configuration worked for you.
      options:
        - label: Select this option if this issue appears to be a regression.
          required: false
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: |
        Suggest a fix or reason for the bug, if you know:
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Logs/Context/Additional Information
      description: |
        Anything else that might be relevant for troubleshooting this bug. Providing context helps us come up with a solution that is most useful in the real world. When applicable, please provide HLOs and compiler commands.
    validations:
      required: false

