---
name: "🐛 Bug Report"
description: Report a bug
title: "(short issue description)"
labels: [bug, needs-triage]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What is the problem? A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: workloadtype
    attributes:
      label: Describe the workload type 
      description: Please mention workload type (e.g.Inference/Training workload or anything else.)
    validations:
      required: true
  - type: textarea
    id: instancetype
    attributes:
      label: Instance Type
      description: |
        Please provide instance type - Inf2.xlarge/trn1.32xlarge/trn2.48xlarge etc?
    validations:
      required: true
  - type: textarea
    id: release
    attributes:
      label: Release version 
      description: |
        Provide Neuron SDK release.        
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: |
        Provide model type, Tutorial links for more context.
        Provide a self-contained, concise snippet of code that can be used to reproduce the issue.
        For more complex issues provide a repo with the smallest sample that reproduces the bug.
        
        Avoid including business logic or unrelated code, it makes diagnosis more difficult.
        The code sample should be an SSCCE. See http://sscce.org/ for details. In short, please provide a code sample that we can copy/paste, run and reproduce.
    validations:
      required: true
  - type: checkboxes
    id: regression
    attributes:
      label: Regression Issue
      description: What is a regression? If it worked in a previous version but doesn't in the latest version, it's considered a
        regression. In this case, please provide specific version number in the report.
      options:
        - label: Select this option if this issue appears to be a regression.
          required: false
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: |
        Suggest a fix/reason for the bug
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Information/Context/Logs
      description: |
        Anything else that might be relevant for troubleshooting this bug. Providing context helps us come up with a solution that is most useful in the real world.
    validations:
      required: false
  - type: input
    id: neuronx-cc-version
    attributes:
      label: neuronx-cc version used
      description: |
        Please provide output of neuronx-cc --version 
    validations:
      required: false
  - type: input
    id: frameworks-used
    attributes:
      label: Framework(s) and their versions used ( PyTorch, etc..)
    validations:
      required: false
