apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  name: us-4-node-config
spec:
  spec:
    devices:
      requests:
      - name: neurons
        deviceClassName: neuron.aws.com
        selectors:
        - cel:
            expression: "device.attributes['neuron.aws.com'].resourceType == 'neuron_node'"
        allocationMode: ExactCount
        count: 1
      config:
      - requests: ["neurons"]
        opaque:
          driver: neuron.aws.com
          parameters:
            apiVersion: neuron.aws.com/v1alphav1
            kind: UltraServerConfig
            ultraserverMode: 4
---
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: vllm
  annotations:
    leaderworkerset.sigs.k8s.io/exclusive-topology: neuron.amazonaws.com/ultraserver-server-id-4
spec:
  rolloutStrategy:
    type: RollingUpdate
    rollingUpdateConfiguration:
      maxUnavailable: 1
      maxSurge: 1
  # Two replica groups of 4 nodes each, i.e. two ultraservers
  replicas: 2
  leaderWorkerTemplate:
    size: 4
    restartPolicy: RecreateGroupOnPodRestart
    leaderTemplate:
      metadata:
        labels:
          role: leader
      spec:
        containers:
          - name: vllm-leader
            image: public.ecr.aws/ubuntu/ubuntu:22.04
            command:
              - sh
              - -c
              - "sleep infinity"
            resources:
              claims:
              - name: one-node-from-ultraserver
        resourceClaims:
        - name: one-node-from-ultraserver
          resourceClaimTemplateName: us-4-node-config
    workerTemplate:
      metadata:
        labels:
          role: worker
      spec:
        containers:
          - name: vllm-worker
            image: public.ecr.aws/ubuntu/ubuntu:22.04
            command:
              - sh
              - -c
              - "sleep infinity"
            resources:
              claims:
              - name: one-node-from-ultraserver
        resourceClaims:
        - name: one-node-from-ultraserver
          resourceClaimTemplateName: us-4-node-config
