#!/usr/bin/env bash

##########################################################################
#  Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0
##########################################################################

echo "" > full_sweep.log
echo "" > full_sweep_results.txt

results=()
for b in $(seq 1 5); do 
    for i in 1 2 4 8 12 16; do 
        python pb2sm_compile.py --batch_size=$b --num_neuroncores=$i | tee -a full_sweep.log;
        results[$b]+=", "`tail -1 full_sweep.log`
    done
done

head="batch"
for i in 1 2 4 8 12 16; do
    head+=", nc${i}"
done 
echo $head | tee -a full_sweep_results.txt
for b in $(seq 1 5); do 
    echo $b${results[$b]} | tee -a full_sweep_results.txt
done
