#!/usr/bin/env bash

##########################################################################
#  Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0
##########################################################################

pip install pillow

# Extract Keras ResNet50 FP32 and check inference
python gen_resnet50_keras.py
python infer_resnet50_keras.py --graph resnet50_fp32_keras.pb
# Optimize fp32 graph for inference before casting
python optimize_for_inference.py --graph resnet50_fp32_keras.pb --out_graph resnet50_fp32_keras_opt.pb
python infer_resnet50_keras.py --graph resnet50_fp32_keras_opt.pb
# Cast full graph to FP16
python fp32tofp16.py  --graph resnet50_fp32_keras_opt.pb --out_graph resnet50_fp16_keras_opt.pb
python infer_resnet50_keras.py --graph resnet50_fp16_keras_opt.pb
# Compile
python pb2sm_compile.py
# Infer
python infer_resnet50_keras_loadtest.py

