# coding=utf-8

""" Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
    SPDX-License-Identifier: MIT-0
    Program to gather information from a system
"""

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mrpc_pb2 as mrpc__pb2


class mrpcStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.paraphrase = channel.unary_unary(
        '/mrpc.mrpc/paraphrase',
        request_serializer=mrpc__pb2.TextPair.SerializeToString,
        response_deserializer=mrpc__pb2.YesNo.FromString,
        )


class mrpcServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def paraphrase(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_mrpcServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'paraphrase': grpc.unary_unary_rpc_method_handler(
          servicer.paraphrase,
          request_deserializer=mrpc__pb2.TextPair.FromString,
          response_serializer=mrpc__pb2.YesNo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'mrpc.mrpc', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
